import type {
  AppUser,
  Category,
  Order,
  OrderStatus,
  PaymentMethod,
  PaymentMethodType,
  Product,
  ProductReview,
  ReturnRequest,
  Subcategory,
} from "./types";

const img = (seed: string, size = 240) => `https://picsum.photos/seed/${seed}/${size}/${size}`;

export const mockSubcategories: Subcategory[] = [
  { id: "sub-1", name: "Smartphones", categoryId: "cat-1", imageUrl: img("smartphones") },
  { id: "sub-2", name: "Laptops", categoryId: "cat-1", imageUrl: img("laptops") },
  { id: "sub-3", name: "Headphones", categoryId: "cat-1", imageUrl: img("headphones") },
  { id: "sub-4", name: "Men", categoryId: "cat-2", imageUrl: img("menwear") },
  { id: "sub-5", name: "Women", categoryId: "cat-2", imageUrl: img("womenwear") },
  { id: "sub-6", name: "Furniture", categoryId: "cat-3", imageUrl: img("furniture") },
  { id: "sub-7", name: "Kitchen", categoryId: "cat-3", imageUrl: img("kitchen") },
  { id: "sub-8", name: "Skincare", categoryId: "cat-4", imageUrl: img("skincare") },
  { id: "sub-9", name: "Fragrance", categoryId: "cat-4", imageUrl: img("fragrance") },
  { id: "sub-10", name: "Fitness", categoryId: "cat-5", imageUrl: img("fitness") },
  { id: "sub-11", name: "Outdoor", categoryId: "cat-5", imageUrl: img("outdoor") },
];

export const mockCategories: Category[] = [
  {
    id: "cat-1",
    name: "Electronics",
    icon: "Smartphone",
    colorHex: "#6C63FF",
    productCount: 5,
    imageUrl: img("electronics"),
    subcategories: ["sub-1", "sub-2", "sub-3"],
  },
  {
    id: "cat-2",
    name: "Fashion",
    icon: "Shirt",
    colorHex: "#FF6B6B",
    productCount: 4,
    imageUrl: img("fashion"),
    subcategories: ["sub-4", "sub-5"],
  },
  {
    id: "cat-3",
    name: "Home & Living",
    icon: "Sofa",
    colorHex: "#22C55E",
    productCount: 3,
    imageUrl: img("homeliving"),
    subcategories: ["sub-6", "sub-7"],
  },
  {
    id: "cat-4",
    name: "Beauty",
    icon: "Sparkles",
    colorHex: "#FFB800",
    productCount: 2,
    imageUrl: img("beauty"),
    subcategories: ["sub-8", "sub-9"],
  },
  {
    id: "cat-5",
    name: "Sports",
    icon: "Dumbbell",
    colorHex: "#0EA5E9",
    productCount: 2,
    imageUrl: img("sports"),
    subcategories: ["sub-10", "sub-11"],
  },
];

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "AuraSound Pro Wireless Headphones",
    price: 189.99,
    originalPrice: 249.99,
    description: "Active noise cancelling over-ear headphones with 40h battery life.",
    category: "cat-1",
    subcategory: "sub-3",
    rating: 4.7,
    reviewCount: 328,
    imageUrl: img("prod1"),
    badge: "Sale",
    inStock: true,
  },
  {
    id: "prod-2",
    name: "Nimbus 14 Ultrabook",
    price: 1299,
    description: "14-inch ultralight laptop, 16GB RAM, 1TB SSD.",
    category: "cat-1",
    subcategory: "sub-2",
    rating: 4.5,
    reviewCount: 112,
    imageUrl: img("prod2"),
    badge: "New",
    inStock: true,
  },
  {
    id: "prod-3",
    name: "Pulse X5 Smartphone",
    price: 749,
    originalPrice: 849,
    description: "6.7-inch AMOLED, triple camera, 5G.",
    category: "cat-1",
    subcategory: "sub-1",
    rating: 4.3,
    reviewCount: 542,
    imageUrl: img("prod3"),
    inStock: false,
  },
  {
    id: "prod-4",
    name: "EchoBuds Mini",
    price: 79.5,
    description: "Compact true-wireless earbuds with wireless charging case.",
    category: "cat-1",
    subcategory: "sub-3",
    rating: 4.1,
    reviewCount: 87,
    imageUrl: img("prod4"),
    inStock: true,
  },
  {
    id: "prod-5",
    name: "Nimbus Dock Hub 8-in-1",
    price: 59.99,
    description: "USB-C hub with HDMI, ethernet and SD card reader.",
    category: "cat-1",
    subcategory: "sub-2",
    rating: 4.6,
    reviewCount: 64,
    imageUrl: img("prod5"),
    inStock: true,
  },
  {
    id: "prod-6",
    name: "Everyday Oversized Hoodie",
    price: 64,
    originalPrice: 89,
    description: "Heavyweight cotton fleece hoodie, unisex fit.",
    category: "cat-2",
    subcategory: "sub-4",
    rating: 4.4,
    reviewCount: 231,
    imageUrl: img("prod6"),
    badge: "Sale",
    inStock: true,
  },
  {
    id: "prod-7",
    name: "Linen Summer Dress",
    price: 98,
    description: "Breathable linen midi dress with side pockets.",
    category: "cat-2",
    subcategory: "sub-5",
    rating: 4.8,
    reviewCount: 143,
    imageUrl: img("prod7"),
    badge: "New",
    inStock: true,
  },
  {
    id: "prod-8",
    name: "Classic Denim Jacket",
    price: 119,
    description: "Washed denim jacket with reinforced stitching.",
    category: "cat-2",
    subcategory: "sub-4",
    rating: 4.2,
    reviewCount: 76,
    imageUrl: img("prod8"),
    inStock: false,
  },
  {
    id: "prod-9",
    name: "Silk Blend Scarf",
    price: 42,
    description: "Lightweight printed scarf, 90x90cm.",
    category: "cat-2",
    subcategory: "sub-5",
    rating: 4.0,
    reviewCount: 29,
    imageUrl: img("prod9"),
    inStock: true,
  },
  {
    id: "prod-10",
    name: "Nordic Lounge Chair",
    price: 349,
    originalPrice: 429,
    description: "Solid oak frame with woven fabric seat.",
    category: "cat-3",
    subcategory: "sub-6",
    rating: 4.6,
    reviewCount: 58,
    imageUrl: img("prod10"),
    badge: "Sale",
    inStock: true,
  },
  {
    id: "prod-11",
    name: "Ceramic Cookware Set (7pc)",
    price: 199,
    description: "Non-stick ceramic pots and pans, induction ready.",
    category: "cat-3",
    subcategory: "sub-7",
    rating: 4.5,
    reviewCount: 191,
    imageUrl: img("prod11"),
    inStock: true,
  },
  {
    id: "prod-12",
    name: "Aroma Diffuser Stone",
    price: 38,
    description: "Ultrasonic diffuser with 7-color ambient light.",
    category: "cat-3",
    subcategory: "sub-6",
    rating: 3.9,
    reviewCount: 44,
    imageUrl: img("prod12"),
    inStock: false,
  },
  {
    id: "prod-13",
    name: "Glow Serum Vitamin C",
    price: 34.5,
    description: "Brightening daily serum with 15% vitamin C.",
    category: "cat-4",
    subcategory: "sub-8",
    rating: 4.7,
    reviewCount: 402,
    imageUrl: img("prod13"),
    badge: "Bestseller",
    inStock: true,
  },
  {
    id: "prod-14",
    name: "Amber Nuit Eau de Parfum",
    price: 129,
    originalPrice: 159,
    description: "Warm amber and vanilla fragrance, 50ml.",
    category: "cat-4",
    subcategory: "sub-9",
    rating: 4.4,
    reviewCount: 97,
    imageUrl: img("prod14"),
    badge: "Sale",
    inStock: true,
  },
  {
    id: "prod-15",
    name: "Adjustable Dumbbell 24kg",
    price: 279,
    description: "Space-saving adjustable dumbbell, 2.5–24kg.",
    category: "cat-5",
    subcategory: "sub-10",
    rating: 4.8,
    reviewCount: 156,
    imageUrl: img("prod15"),
    inStock: true,
  },
  {
    id: "prod-16",
    name: "TrailLite 40L Backpack",
    price: 149,
    description: "Weatherproof hiking backpack with rain cover.",
    category: "cat-5",
    subcategory: "sub-11",
    rating: 4.3,
    reviewCount: 63,
    imageUrl: img("prod16"),
    badge: "New",
    inStock: false,
  },
];

export const mockUsers: AppUser[] = [
  {
    id: "user-1",
    name: "Layla Hassan",
    email: "layla.hassan@example.com",
    phone: "+20 100 442 8891",
    address: "12 Nile View St, Zamalek, Cairo",
    avatarUrl: img("layla", 96),
  },
  {
    id: "user-2",
    name: "Marcus Bennett",
    email: "m.bennett@example.com",
    phone: "+1 415 220 7781",
    address: "884 Folsom St, San Francisco, CA",
    avatarUrl: img("marcus", 96),
  },
  {
    id: "user-3",
    name: "Sofia Rossi",
    email: "sofia.rossi@example.com",
    phone: "+39 340 118 2277",
    address: "Via Torino 21, Milano",
    avatarUrl: img("sofia", 96),
  },
  {
    id: "user-4",
    name: "Daniel Okafor",
    email: "d.okafor@example.com",
    phone: "+234 802 771 0043",
    address: "5 Adeola Odeku, Victoria Island, Lagos",
    avatarUrl: img("daniel", 96),
  },
  {
    id: "user-5",
    name: "Emma Lindqvist",
    email: "emma.l@example.com",
    phone: "+46 70 552 8890",
    address: "Sveavägen 44, Stockholm",
    avatarUrl: img("emma", 96),
  },
  {
    id: "user-6",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@example.com",
    phone: "+81 90 4412 9987",
    address: "3-2-1 Shibuya, Tokyo",
    avatarUrl: img("yuki", 96),
  },
];

export const mockPaymentMethods: PaymentMethod[] = [
  {
    id: "pm-1",
    type: "visa",
    lastFour: "4242",
    expiry: "09/28",
    holderName: "Layla Hassan",
    isDefault: true,
  },
  {
    id: "pm-2",
    type: "mastercard",
    lastFour: "8891",
    expiry: "01/27",
    holderName: "Marcus Bennett",
    isDefault: false,
  },
  {
    id: "pm-3",
    type: "amex",
    lastFour: "0031",
    expiry: "05/29",
    holderName: "Sofia Rossi",
    isDefault: false,
  },
  { id: "pm-4", type: "paypal", holderName: "Daniel Okafor", isDefault: false },
  { id: "pm-5", type: "cashOnDelivery", isDefault: false },
];

const statuses: OrderStatus[] = ["processing", "shipped", "delivered", "cancelled"];

function daysAgo(n: number) {
  const d = new Date("2026-08-20T12:00:00Z");
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function buildOrders(): Order[] {
  const orders: Order[] = [];
  for (let i = 0; i < 28; i++) {
    const user = mockUsers[i % mockUsers.length]!;
    const status =
      i % 11 === 0 ? "cancelled" : i % 3 === 0 ? "processing" : i % 3 === 1 ? "shipped" : "delivered";
    const itemCount = (i % 3) + 1;
    const items = Array.from({ length: itemCount }, (_, k) => {
      const p = mockProducts[(i * 3 + k) % mockProducts.length]!;
      return {
        productId: p.id,
        name: p.name,
        imageUrl: p.imageUrl,
        price: p.price,
        quantity: ((i + k) % 2) + 1,
      };
    });
    const total = Number(
      items.reduce((sum, it) => sum + it.price * it.quantity, 0).toFixed(2),
    );
    const date = daysAgo(i);
    const history: { status: OrderStatus; date: string }[] = [
      { status: "processing", date },
    ];
    if (status === "shipped" || status === "delivered")
      history.push({ status: "shipped", date: daysAgo(Math.max(0, i - 1)) });
    if (status === "delivered")
      history.push({ status: "delivered", date: daysAgo(Math.max(0, i - 3)) });
    if (status === "cancelled") history.push({ status: "cancelled", date: daysAgo(Math.max(0, i - 1)) });

    orders.push({
      id: `ORD-${(10248 + i).toString()}`,
      date,
      total,
      status: status as OrderStatus,
      items,
      estimatedDelivery: daysAgo(i - 5),
      ...(status === "delivered" ? { deliveredDate: daysAgo(Math.max(0, i - 3)) } : {}),
      paymentMethod: mockPaymentMethods[i % mockPaymentMethods.length]!,
      userId: user.id,
      customerName: user.name,
      shippingAddress: user.address,
      history,
    });
  }
  return orders;
}

export const mockOrders: Order[] = buildOrders();

export const mockReturns: ReturnRequest[] = [
  {
    id: "RET-2041",
    orderId: "ORD-10251",
    productName: "Pulse X5 Smartphone",
    requestedDate: daysAgo(2),
    refundAmount: 749,
    status: "inReview",
    reason: "Arrived with a cracked screen protector.",
  },
  {
    id: "RET-2042",
    orderId: "ORD-10253",
    productName: "Everyday Oversized Hoodie",
    requestedDate: daysAgo(4),
    refundAmount: 64,
    status: "refunded",
    reason: "Wrong size delivered.",
  },
  {
    id: "RET-2043",
    orderId: "ORD-10257",
    productName: "Ceramic Cookware Set (7pc)",
    requestedDate: daysAgo(6),
    refundAmount: 199,
    status: "inReview",
    reason: "Changed my mind.",
  },
  {
    id: "RET-2044",
    orderId: "ORD-10260",
    productName: "Amber Nuit Eau de Parfum",
    requestedDate: daysAgo(9),
    refundAmount: 129,
    status: "rejected",
    reason: "Seal opened, not eligible for return.",
  },
  {
    id: "RET-2045",
    orderId: "ORD-10262",
    productName: "TrailLite 40L Backpack",
    requestedDate: daysAgo(11),
    refundAmount: 149,
    status: "inReview",
    reason: "Zipper defective after first use.",
  },
  {
    id: "RET-2046",
    orderId: "ORD-10266",
    productName: "AuraSound Pro Wireless Headphones",
    requestedDate: daysAgo(14),
    refundAmount: 189.99,
    status: "refunded",
    reason: "Right earcup not charging.",
  },
];

export const mockReviews: ProductReview[] = [
  {
    id: "rev-1",
    productId: "prod-1",
    userId: "user-1",
    name: "Layla Hassan",
    rating: 5,
    date: daysAgo(1),
    text: "Noise cancelling is genuinely excellent — battery easily lasts a week of commutes.",
    verified: true,
    helpfulCount: 42,
  },
  {
    id: "rev-2",
    productId: "prod-3",
    userId: "user-2",
    name: "Marcus Bennett",
    rating: 3,
    date: daysAgo(3),
    text: "Great screen but the battery drains fast with 5G on.",
    verified: true,
    helpfulCount: 17,
  },
  {
    id: "rev-3",
    productId: "prod-7",
    userId: "user-3",
    name: "Sofia Rossi",
    rating: 5,
    date: daysAgo(5),
    text: "Beautiful fabric and the pockets are a lifesaver. True to size.",
    verified: true,
    helpfulCount: 31,
  },
  {
    id: "rev-4",
    productId: "prod-11",
    userId: "user-4",
    name: "Daniel Okafor",
    rating: 4,
    date: daysAgo(7),
    text: "Cooks evenly, cleans easily. The lids feel a bit light.",
    verified: false,
    helpfulCount: 9,
  },
  {
    id: "rev-5",
    productId: "prod-13",
    userId: "user-5",
    name: "Emma Lindqvist",
    rating: 5,
    date: daysAgo(8),
    text: "Visible difference in three weeks. No irritation at all.",
    verified: true,
    helpfulCount: 58,
  },
  {
    id: "rev-6",
    productId: "prod-15",
    userId: "user-6",
    name: "Yuki Tanaka",
    rating: 2,
    date: daysAgo(10),
    text: "Adjustment dial jammed after two weeks of use. Support was slow.",
    verified: true,
    helpfulCount: 24,
  },
  {
    id: "rev-7",
    productId: "prod-6",
    userId: "user-1",
    name: "Layla Hassan",
    rating: 4,
    date: daysAgo(12),
    text: "Very warm and soft, but it shrank slightly after washing.",
    verified: false,
    helpfulCount: 6,
  },
  {
    id: "rev-8",
    productId: "prod-2",
    userId: "user-2",
    name: "Marcus Bennett",
    rating: 5,
    date: daysAgo(15),
    text: "Fast, silent and light. Best laptop I've owned for travel.",
    verified: true,
    helpfulCount: 38,
  },
];

export const paymentMethodLabels: Record<PaymentMethodType, string> = {
  visa: "Visa",
  mastercard: "Mastercard",
  amex: "American Express",
  paypal: "PayPal",
  cashOnDelivery: "Cash on Delivery",
};

export const orderStatusOrder: OrderStatus[] = statuses;